USE college_portal;

CREATE TABLE IF NOT EXISTS mail_inbox (
  id INT AUTO_INCREMENT PRIMARY KEY,
  toRegNumber VARCHAR(12) NOT NULL,
  subject VARCHAR(255) NOT NULL,
  body TEXT NOT NULL,
  sentAt DATETIME DEFAULT CURRENT_TIMESTAMP,
  isRead TINYINT(1) DEFAULT 0
);
